/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logica.Circulo;
import Logica.Conexo;
import Logica.Euler;
import Logica.Grafo;
import Logica.Hamilton;
import Logica.Linea;
import java.awt.*;
import javax.swing.JOptionPane;
import java.util.*;


/**
 *
 * @author orarj
 */
public class NewJFrame extends javax.swing.JFrame {
    Circulo circulo = new Circulo();
    Grafo nuevo = new Grafo();
    Linea linea = new Linea();
    int[][] coordenadas = new int[2][20];
    Circulo nodoInicio = null;
    Circulo nodoFin = null;
   
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Canvas = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnConexo = new javax.swing.JButton();
        btnHamilton = new javax.swing.JButton();
        btnEuler = new javax.swing.JButton();
        btnMatriz = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        btnCaminoCorto = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Canvas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Canvas.setAutoscrolls(true);
        Canvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CanvasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CanvasLayout = new javax.swing.GroupLayout(Canvas);
        Canvas.setLayout(CanvasLayout);
        CanvasLayout.setHorizontalGroup(
            CanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        CanvasLayout.setVerticalGroup(
            CanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        jButton2.setText("Crear Arista");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnConexo.setText("Conexo");
        btnConexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConexoActionPerformed(evt);
            }
        });

        btnHamilton.setText("Hamilton");
        btnHamilton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHamiltonActionPerformed(evt);
            }
        });

        btnEuler.setText("Euler");
        btnEuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEulerActionPerformed(evt);
            }
        });

        btnMatriz.setText("Imprimir Matriz");
        btnMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatrizActionPerformed(evt);
            }
        });

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        btnCaminoCorto.setText("Camino mas corto");
        btnCaminoCorto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaminoCortoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Canvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHamilton)
                                    .addComponent(btnEuler, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConexo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCaminoCorto)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMatriz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(btnConexo)
                        .addGap(11, 11, 11)
                        .addComponent(btnHamilton)
                        .addGap(9, 9, 9)
                        .addComponent(btnEuler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCaminoCorto)
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Canvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CanvasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CanvasMouseClicked
        // TODO add your handling code here:
        int x = evt.getX();
	int y = evt.getY();
        
        circulo.setX(x);
        circulo.setY(y);
        Graphics g = Canvas.getGraphics();
        circulo.circulo(g);
        circulo.setNum(circulo.getNum()+1);
        circulo.numero(g);        
        
        coordenadas[0][nuevo.getNoVertices()]=x+10; 
        coordenadas[1][nuevo.getNoVertices()]=y+10;
        
        
        nuevo.setNoVertices(nuevo.getNoVertices()+1);
        nuevo.rellenar();
        
        
        
    }//GEN-LAST:event_CanvasMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /*Arista arista = new Arista();
        arista.setVisible(true);*/
        // CrearArista
        int a = Integer.parseInt(JOptionPane.showInputDialog("1 Grafo #:"));
        int b = Integer.parseInt(JOptionPane.showInputDialog("2 Grafo #:"));
        int num = Integer.parseInt(JOptionPane.showInputDialog("3 valor #:"));

        linea.setX1(coordenadas[0][a-1]);
        linea.setX2(coordenadas[0][b-1]);
        linea.setY1(coordenadas[1][a-1]);
        linea.setY2(coordenadas[1][b-1]);
        linea.setNum(num);
        
        Graphics g = Canvas.getGraphics();
        linea.Linea(g);
        linea.numero(g);

        if(a != b){ 
            nuevo.aristaMatriz(a-1, b-1);
            nuevo.aristaMatriz(b-1, a-1);
            nuevo.valorAristaMatriz(a-1, b-1,num);
            nuevo.valorAristaMatriz(b-1, a-1,num);
        }else{
            nuevo.aristaMatriz(a-1, b-1);
            nuevo.valorAristaMatriz(a-1, b-1,num);
        } 
        
        
        
        
       /* for(int i = 0; i < nuevo.getValorArista().length;i++){
            String aux = "";
            for(int j = 0; j < nuevo.getValorArista()[0].length;j++){
                aux = aux + Integer.toString(nuevo.getValorArista()[i][j]);
            }
            System.out.println(aux);
        }
        System.out.println(" ");*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnConexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConexoActionPerformed
        // GRAFO CONEXO
        int[][] matriz = nuevo.getMatrizDeAdyacencia();
        Conexo conexo = new Conexo();
        conexo.setMatrizDeAdyacencia(matriz);
        conexo.probar();
 
    }//GEN-LAST:event_btnConexoActionPerformed

    private void btnMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatrizActionPerformed
        // IMPRIMIR MATRIZ
        int[][] matriz = nuevo.getMatrizDeAdyacencia();
        for (int x=0; x < matriz.length; x++) {
        System.out.print("|");
        for (int y=0; y < matriz[x].length; y++) {
          System.out.print (matriz[x][y]);
          if (y!=matriz[x].length-1) System.out.print("\t");
        }
        System.out.println("|");
      } 
        
    }//GEN-LAST:event_btnMatrizActionPerformed

    private void btnHamiltonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamiltonActionPerformed
        // HALMITONEANO
        Hamilton x = new Hamilton(nuevo);
        x.setMatrizDeAdyacencia(nuevo.getMatrizDeAdyacencia());
        int b = Integer.parseInt(JOptionPane.showInputDialog("Nodo inicial:"));
        x.probarHamilton(b-1);
    }//GEN-LAST:event_btnHamiltonActionPerformed

    private void btnEulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEulerActionPerformed
        // EULER
        Euler y = new Euler();
        y.setMatrizDeAdyacencia(nuevo.getMatrizDeAdyacencia());
        int a = Integer.parseInt(JOptionPane.showInputDialog("Nodo inicial:"));
        y.probarEuler(a-1);
    }//GEN-LAST:event_btnEulerActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // limpiar canvas    
        
        Canvas.removeAll();
        
        Canvas.revalidate();
        Canvas.repaint();   
        
        circulo.setNum(circulo.getNum()* 0);
        nuevo.setNoVertices(nuevo.getNoVertices()* 0);
   
        
    }//GEN-LAST:event_LimpiarActionPerformed

    private void btnCaminoCortoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaminoCortoActionPerformed
        // TODO add your handling code here:
        int inicio = Integer.parseInt(JOptionPane.showInputDialog("Nodo1 :"));
        int fin = Integer.parseInt(JOptionPane.showInputDialog("Nodo2 :"));
        nuevo.caminoMasCorto(inicio, fin);
        
        
        /*for(int i = 0; i < nuevo.getValorArista().length;i++){
            String aux = "";
            for(int j = 0; j < nuevo.getValorArista()[0].length;j++){
                aux = aux + Integer.toString(nuevo.getValorArista()[i][j]);
            }
            System.out.println(aux);
        }
        System.out.println(" ");*/
    }//GEN-LAST:event_btnCaminoCortoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Canvas;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton btnCaminoCorto;
    private javax.swing.JButton btnConexo;
    private javax.swing.JButton btnEuler;
    private javax.swing.JButton btnHamilton;
    private javax.swing.JButton btnMatriz;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
